/* 
SUM COUNT MIN MAX AVG
---
SELECT
SUM (PRICE), COUNT(ID), MIN(PRICE), MAX(PRICE), AVG(PRICE)
FROM TABLOADI
----
*/

SELECT SUM(LINENET) FROM SALES WHERE BRANCH='Kocaeli Subesi'
SELECT SUM(LINENET), COUNT(*) FROM SALES WHERE BRANCH='Kocaeli Subesi'
SELECT SUM(LINENET), COUNT(*), MIN(LINENET), MAX(LINENET) FROM SALES WHERE BRANCH='Kocaeli Subesi'

/* LINENET ürün satış fiyatını gösteriyor. */

SELECT SUM(LINENET) AS TOPLAMSATIS, COUNT(*) AS SATIRSAYISI, MIN(LINENET) AS ENUCUZFIYAT, MAX(LINENET) AS ENPAHALIFIYAT FROM SALES WHERE BRANCH='Kocaeli Subesi'

/* blabla AS ALANADI    yaparak gelen alanların üstüne isim ekledik. */

  
