SELECT * FROM CUSTOMER WHERE CITY = 'İSTANBUL' 
SELECT * FROM CUSTOMER WHERE CUSTOMERNAME LIKE 'HÜSEYİN%'

SELECT * FROM CUSTOMER WHERE CITY = 'İSTANBUL' AND CUSTOMERNAME LIKE 'HÜSEYİN%'
SELECT * FROM CUSTOMER WHERE CITY = 'İSTANBUL' OR CUSTOMERNAME LIKE 'HÜSEYİN%'
SELECT * FROM CUSTOMER WHERE CITY = 'İSTANBUL' OR CUSTONMERNAME LIKE 'HÜSEYİN%'
