--ASCII VE CHAR FONKSIYONLARI
SELECT ASCII('A')
SELECT CHAR(65)

--SUBSTRING:BİR STRINGIN İÇERİSİNDE BELLİ BİR NOKTAYA KADAR SEÇMEYİ SAĞLIYOR.(STRING,BAŞLANGIÇ KARAKTERİ,SEÇİLECEK KARAKTER SAYISI)
SELECT SUBSTRING('AHMET EYÜP USLU',1,5)

--CHARINDEX BİR INDEX İÇERİSİNDE BASKA BİR STRING BULDURUM POZISYONUNU SÖYLER.
SELECT CHARINDEX('T','AHMET EYUP USLU',1)

--CONCAT
SELECT CONCAT('AHMET ','EYÜP ','USLU')
SELECT CONCAT_WS(' ','AHMET','EYÜP','USLU')

SELECT
USERNAME_+' '+PASSWORD_+' '+NAMESURNAME
CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME),
* FROM USER_




--FORMAT 
SELECT FORMAT (getdate(),'d','en-US')





--LEFT, RIGHT, LEN
SELECT LEFT('AHMET EYÜP USLU',5)
SELECT RIGHT('AHMET EYÜP USLU',4)
SELECT LEN('1234567890')

SELECT LEFT('AHMET EYÜP USLU',10)
SELECT RIGHT('AHMET EYÜP USLU',4)

SELECT LEFT('AHMET EYÜP USLU', CHARINDEX(' ','AHMET EYÜP USLU'))
SELECT RIGHT('AHMET EYÜP USLU', LEN('AHMET EYÜP USLU')-CHARINDEX(' ','AHMET EYÜP USLU'))

SELECT
LEFT(NAMESURNAME, CHARINDEX(' ',NAMESURNAME)),RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME))
FROM USER_






--TRIM,LTRIM,RTRIM  left ve right da tek taraflı bosluk siliyo

SELECT TRIM(' AHMET EYÜP USLU ')  --BOŞLUKLARI TEMİZLEDİ




--lower upper reverse replicate
SELECT LOWER('AHMET')  --karakterleri gücült
SELECT UPPER('uslu')   --karakterleri büyült
SELECT REVERSE('AHMET')   --TERS YAZDIR TEMHA
SELECT REPLICATE('0',10)    --STANDART KARAKTER SAYISINI TUTTURMAMIZ GEREKTİĞİNDE KULLANIRIZ. 10 TANE 0 KOYAR BAŞTAKİ KODTA.

SELECT *,REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO) FROM TEST
UPDATE TEST SET SIRANO2=REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO)



-- REPLACE FONKSIYONU
SELECT 'AHMET EYÜP USLU'
SELECT REPLACE('AHMET EYÜP USLU', 'AHMET EYÜP','AHMET')




-- BIR PARAGRAF İÇERİSİNDE BİR KELİME DEĞİŞTİRME
DECLARE @CUMLE AS VARCHAR(MAX)
SET @CUMLE='QWEWQEQEQEQEQE PARAGRAF OLDUĞUNU VAR SAYALIM'
SET @CUMLE=REPLACE(@CUMLE,'SAYALIM','SAYDIK')
SELECT @CUMLE 





--BIR PARAGRAF İÇERİSİNDE KELİME SAYISINI BULMA
DECLARE @CUMLE AS VARCHAR(MAX)
SET @CUMLE='QWEWQEQEQEQEQE PARAGRAF OLDUĞUNU VAR SAYALIM VAR'

declare @LEN1 AS INT 
SET @LEN1=LEN(@CUMLE)
DECLARE @LEN2 AS INT
SET @CUMLE=REPLACE(@CUMLE,'VAR','')
SET @LEN2=LEN(@CUMLE)

SELECT(@LEN1-@LEN2)/LEN('VAR')
