--BİR KULLANICININ YAPTIĞI ALIŞVERİŞ SAYISI,ADEDİ VE TOPLAM TUTARI
SELECT U.NAMESURNAME, COUNT(DISTINCT BASKETID) COUNT(BD.ID),SUM(BD.AMOUNT),SUM(TOTAL)
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID

GROUP BY U.NAMESURNAME




--BİR ŞEHİRDEN YAPILAN ALIŞVERİŞ SAYISI,ADEDİ VE TOPLAM TUTARI
SELECT C.CITY, COUNT(DISTINCT BASKETID) COUNT(BD.ID),SUM(BD.AMOUNT),SUM(TOTAL)
FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
INNER JOIN ITEM I ON I.ID=BD.ID
INNER JOIN ORDER_ O ON O.BASKETID=B.ID
INNER JOIN ADDRES A ON A.ID=O.ADDRESSID
INNER JOIN CITY C ON C.ID=A.CITYID
INNER JOIN TOWN T ON T.ID=A.TOWNID

GROUP BY C.CITY
