--SUBQUERY
SELECT U.ID,U.NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0


--JOIN
SELECT U.NAMESURNAME,COUNT(B.ID)
FROM USER_ U 
JOIN BASKET B ON B.USERID=U.ID
GROUP BY U.NAMESURNAME
