-- EN SON SİPARİŞ VERDİĞİ TARİHİ GETİRME
SELECT ID,NAMESURNAME,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE
FROM USER_ U





----SUBQUERY ile müşteri bilgisi getirme
SELECT ID,NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) AS BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) AS LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID))

FROM USER_ U
WHERE 
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0






--AYNISININ JOINLE YAPILANI
SELECT U.ID,U.NAMESURNAME,
COUNT(B.ID) AS BASKETCOUNT,MIN(B.CREATEDDATE) AS FIRSTBASKETDATE,
MAX(B.CREATEDDATE) AS LASTBASKETDATE,SUM(BD.TOTAL) AS TOTAL,COUNT(BD.ID) AS ITEMCOUNT_

FROM USER_ U
INNER JOIN BASKET B ON B.USERID=U.ID
INNER JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
 
GROUP BY U.ID,U.NAMESURNAME 
