SELECT U.*
FROM USER_ U
WHERE U.ID=1



-------------

SELECT U.*,A.ADDRESSTEXT
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
WHERE U.ID=1


----------------------



SELECT U.*,A.*,C.CITY,T.TOWN
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

WHERE U.ID=1



----------------------------




SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
C.CITY AS SEHIR,
T.TOWN AS ILCE,
D.DISTRICT AS MAHALLE,
A.ADDRESSTEXT AS ACIKADRES
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

WHERE U.ID=1
