SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

WHERE U.ID=1

GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2




-- GENEL KULLANIMI VE ADRES SAYISINA GÖRE AZALAN SIRALARSAK

SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID


GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2

ORDER BY COUNT(A.ID) DESC




--ADRES SAYISI 1 OLANLARI ÇIKARMA
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID


GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2

HAVING COUNT(A.ID)=1












--HANGİ ŞEHİRDE KAÇ TANE KULLANICI VAR SORUSU İÇİN:
SELECT 
C.CITY,COUNT(U.ID)
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID


GROUP BY 
C.CITY
ORDER BY 2 DESC





--ADRES SAYISINDA FARKLI ŞEHİR SAYISINI SAYDIRMA
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI,
COUNT (DISTINCT C.CITY) AS SEHIR_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID


GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2










--AYNI ŞEHİRDE İKİ FARKLI ADRESİ OLANLARI BELİRLEME
SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI,
COUNT (DISTINCT C.CITY) AS SEHIR_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID


GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2

HAVING COUNT(A.ID)<>COUNT(DISTINCT C.CITY)

