SELECT U.USERNAME_ KULLANICIADI,
U.NAMESURNAME AS ADSOYADI,
U.EMAIL AS EMAIL,
U.TELNR1 AS TELEFON1,
U.TELNR2 AS TELEFON2,
COUNT(A.ID) AS ADRES_SAYISI
FROM USER_ U
JOIN ADDRES A ON U.ID=A.USERID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID

WHERE U.ID=1

GROUP BY 
U.USERNAME_,
U.NAMESURNAME,
U.EMAIL,
U.TELNR1,
U.TELNR2





